# Generated by Django 4.0.3 on 2026-09-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_automobile_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobile',
            name='has_open_recall',
            field=models.BooleanField(default=False),
        ),
    ]
